apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Idem Project
  description: Idem reduces your cloud configuration to data – for you! Instead of
    Infrastructure as Code, Idem delivers Infrastructure as Data. The cloud
    becomes simplified, easier to maintain, easier to discover, and easier to
    use.
  links:
    - url: https://www.idemproject.io
spec:
  type: service
  lifecycle: experimental
  owner: hello
