apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Backstage
  links:
    - title: Homepage
      url: https://backstage.io/
    - title: Crunchbase
      url: https://www.crunchbase.com/organization/cloud-native-computing-foundation
    - title: Slack/Discord
      url: https://discord.gg/backstage-687207715902193673
  tags:
    - developerportals
    - idp
    - servicecatalog
    - observability
  annotations:
    backstage.io/source-location: $url:https://github.com/backstage/backstage
spec:
  type: service
  lifecycle: production
  owner: CNCF
  accepted: 2020-09-08
  category: App Definition and Development
  subcategory: Application Definition & Image Build
  status: incubating
  logo: backstage.svg
  maturity:
    sandbox_date: 2020-09-08
    incubation_date: 2022-03-15
