apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: CNI-Genie
  links:
    - title: Homepage
      url: https://cnigenie.netlify.app
    - title: Crunchbase
      url: https://www.crunchbase.com/organization/cloud-native-computing-foundation
  annotations:
    backstage.io/source-location: $url:https://github.com/cni-genie/CNI-Genie
spec:
  type: service
  lifecycle: production
  owner: CNCF
  accepted: 2020-06-25
  category: Runtime
  subcategory: Cloud Native Network
  status: sandbox
  logo: cni-genie.svg
  maturity:
    sandbox_date: 2020-06-25
