apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Devfile
  links:
    - title: Homepage
      url: https://devfile.io
    - title: Crunchbase
      url: https://www.crunchbase.com/organization/cloud-native-computing-foundation
    - title: Slack/Discord
      url: https://kubernetes.slack.com/messages/devfile
  tags:
    - kubernetes
    - applicationlifecycle
    - developerenvironment
    - containers
  annotations:
    backstage.io/source-location: $url:https://github.com/devfile/api
spec:
  type: service
  lifecycle: production
  owner: CNCF
  accepted: 2022-01-11
  category: App Definition and Development
  subcategory: Application Definition & Image Build
  status: sandbox
  logo: devfile.svg
  maturity:
    sandbox_date: 2022-01-11
