apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: DevStream
  links:
    - title: Homepage
      url: https://www.devstream.io/
    - title: Crunchbase
      url: https://www.crunchbase.com/organization/cloud-native-computing-foundation
    - title: Slack/Discord
      url: https://cloud-native.slack.com/messages/devstream
  annotations:
    backstage.io/source-location: $url:https://github.com/devstream-io/devstream
spec:
  type: service
  lifecycle: production
  owner: CNCF
  accepted: 2022-06-17
  category: Provisioning
  subcategory: Automation & Configuration
  status: sandbox
  logo: devstream.svg
  maturity:
    sandbox_date: 2022-06-17
