apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Harbor
  links:
    - title: Homepage
      url: https://goharbor.io/
    - title: Crunchbase
      url: https://www.crunchbase.com/organization/cloud-native-computing-foundation
  annotations:
    landscape3.io/accepted: 2018-07-31
    landscape3.io/category: Provisioning
    landscape3.io/subcategory: Container Registry
    landscape3.io/cncfStatus: graduated
spec:
  type: service
  lifecycle: production
  owner: CNCF
