apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Hexa
  links:
    - title: Homepage
      url: https://hexaorchestration.org/
    - title: Crunchbase
      url: https://www.crunchbase.com/organization/cloud-native-computing-foundation
    - title: Twitter
      url: https://twitter.com/HexaPolicy
  annotations:
    backstage.io/source-location: $url:https://github.com/hexa-org/policy-orchestrator
spec:
  type: service
  lifecycle: production
  owner: CNCF
  accepted: 2022-07-26
  category: Provisioning
  subcategory: Security & Compliance
  status: sandbox
  logo: hexa.svg
  maturity:
    sandbox_date: 2022-07-26
