apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: HwameiStor
  description: Hwameistor is an HA local storage system for cloud-native stateful workloads
  links:
    - title: Homepage
      url: https://hwameistor.io/
    - title: Crunchbase
      url: https://www.crunchbase.com/organization/cloud-native-computing-foundation
    - title: Twitter
      url: https://twitter.com/daocloud_io
    - title: Slack/Discord
      url: https://cloud-native.slack.com/messages/hwameistor
  annotations:
    backstage.io/source-location: $url:https://github.com/hwameistor/hwameistor
spec:
  type: service
  lifecycle: production
  owner: CNCF
  accepted: 2023-06-22
  category: Runtime
  subcategory: Cloud Native Storage
  status: sandbox
  logo: hwameistor.svg
  maturity:
    sandbox_date: 2023-06-22
