apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Inclavare-Containers
  links:
    - title: Homepage
      url: https://github.com/inclavare-containers/
    - title: Crunchbase
      url: https://www.crunchbase.com/organization/cloud-native-computing-foundation
    - title: Slack/Discord
      url: https://cloud-native.slack.com/archives/C02HJJ81BD5
  annotations:
    backstage.io/source-location: $url:https://github.com/inclavare-containers/inclavare-containers
spec:
  type: service
  lifecycle: production
  owner: CNCF
  accepted: 2021-09-14
  category: Runtime
  subcategory: Container Runtime
  status: sandbox
  logo: inclavare.svg
  maturity:
    sandbox_date: 2021-09-14
