apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: k8gb
  links:
    - title: Homepage
      url: https://www.k8gb.io
    - title: Crunchbase
      url: https://www.crunchbase.com/organization/cloud-native-computing-foundation
    - title: Slack/Discord
      url: https://cloud-native.slack.com/messages/k8gb
  tags:
    - multicluster
    - loadbalancing
    - gslb
    - dns
    - kubernetes
    - coredns
    - globalserviceloadbalancing
    - globaltrafficmanagement
  annotations:
    backstage.io/source-location: $url:https://github.com/k8gb-io/k8gb
spec:
  type: service
  lifecycle: production
  owner: CNCF
  accepted: 2021-03-30
  category: Orchestration & Management
  subcategory: Coordination & Service Discovery
  status: sandbox
  logo: k8gb.svg
  maturity:
    sandbox_date: 2021-03-30
