apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Knative-Serverless
  description: 'Knative is a developer-focused serverless application layer which
    is a great complement to the existing Kubernetes application constructs.
    Knative consists of three components: an HTTP-triggered autoscaling
    container runtime called “Knative Serving”, a CloudEvents-over-HTTP
    asynchronous routing layer called “Knative Eventing”, and a
    developer-focused function framework which leverages the Serving and
    Eventing components, called "Knative Functions".'
  links:
    - title: Homepage
      url: https://knative.dev
    - title: Crunchbase
      url: https://www.crunchbase.com/organization/cloud-native-computing-foundation
    - title: Twitter
      url: https://twitter.com/KnativeProject
    - title: Slack/Discord
      url: https://slack.cncf.io
  tags:
    - serverless
    - cloudevents
    - functions
    - scaling
    - applications
  annotations:
    backstage.io/source-location: $url:https://github.com/knative/serving
spec:
  type: service
  lifecycle: production
  owner: CNCF
  accepted: 2022-03-02
  category: Serverless
  subcategory: Installable Platform
  status: incubating
  logo: knative.svg
  maturity:
    sandbox_date: 2022-03-02
    incubation_date: 2022-03-02
