apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Konveyor
  links:
    - title: Homepage
      url: https://www.konveyor.io/
    - title: Crunchbase
      url: https://www.crunchbase.com/organization/cloud-native-computing-foundation
  annotations:
    landscape3.io/accepted: 2022-07-26
    landscape3.io/category: App Definition and Development
    landscape3.io/subcategory: Application Definition & Image Build
    landscape3.io/cncfStatus: sandbox
spec:
  type: service
  lifecycle: production
  owner: CNCF
