apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Koordinator
  description: QoS based scheduling system for hybrid orchestration workloads on
    Kubernetes, bringing workloads the best layout and status.
  links:
    - title: Homepage
      url: https://koordinator.sh
    - title: Crunchbase
      url: https://www.crunchbase.com/organization/alibaba-cloud
  annotations:
    backstage.io/source-location: $url:https://github.com/koordinator-sh/koordinator
spec:
  type: service
  lifecycle: production
  owner: CNCF
  accepted: 2024-04-16
  category: Orchestration & Management
  subcategory: Scheduling & Orchestration
  status: sandbox
  logo: Koordinator.svg
  maturity:
    sandbox_date: 2024-04-16
