apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Krkn
  description: Chaos testing tool for Kubernetes to identify bottlenecks and
    improve resilience and performance under failure conditions.
  links:
    - title: Homepage
      url: https://krkn-chaos.github.io/krkn
    - title: Crunchbase
      url: https://www.crunchbase.com/organization/red-hat
    - title: Slack/Discord
      url: https://kubernetes.slack.com/messages/C05SFMHRWK1
  annotations:
    backstage.io/source-location: $url:https://github.com/krkn-chaos/krkn
spec:
  type: service
  lifecycle: production
  owner: CNCF
  accepted: 2023-12-19
  category: Observability and Analysis
  subcategory: Chaos Engineering
  status: sandbox
  logo: krkn.svg
  maturity:
    sandbox_date: 2023-12-19
