apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Kubernetes
  description: Kubernetes is an open-source system for automating deployment,
    scaling, and management of containerized applications
  links:
    - title: Homepage
      url: https://kubernetes.io/
    - title: Crunchbase
      url: https://www.crunchbase.com/organization/cloud-native-computing-foundation
    - title: Twitter
      url: https://twitter.com/kubernetesio
    - title: Slack/Discord
      url: http://slack.k8s.io/
  annotations:
    backstage.io/source-location: $url:https://github.com/kubernetes/kubernetes
spec:
  type: service
  lifecycle: production
  owner: CNCF
  accepted: 2016-03-10
  category: CNAI
  subcategory: General Orchestration
  status: graduated
  logo: kubernetes.svg
  maturity:
    sandbox_date: 2016-03-10
    incubation_date: 2016-03-10
    graduation_date: 2018-03-06
