apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Kubeflow
  description: Kubeflow is the foundation of tools for AI Platforms on Kubernetes.
  links:
    - title: Homepage
      url: https://kubeflow.org
    - title: Crunchbase
      url: https://www.crunchbase.com/organization/cloud-native-computing-foundation
    - title: Twitter
      url: https://twitter.com/kubeflow
    - title: Slack/Discord
      url: http://slack.cncf.io/
  annotations:
    backstage.io/source-location: $url:https://github.com/kubeflow/kubeflow
spec:
  type: service
  lifecycle: production
  owner: CNCF
  accepted: 2023-07-25
  category: Orchestration & Management
  subcategory: Scheduling & Orchestration
  status: incubating
  logo: kubeflow.svg
  maturity:
    sandbox_date: 2023-07-25
    incubation_date: 2023-07-25
