apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: KubeEdge
  links:
    - title: Homepage
      url: https://kubeedge.io/en/
    - title: Crunchbase
      url: https://www.crunchbase.com/organization/cloud-native-computing-foundation
    - title: Twitter
      url: https://twitter.com/KubeEdge
    - title: Slack/Discord
      url: https://kubeedge.slack.com/
  tags:
    - edge
    - iotdevice
  annotations:
    backstage.io/source-location: $url:https://github.com/kubeedge/kubeedge
spec:
  type: service
  lifecycle: production
  owner: CNCF
  accepted: 2019-03-18
  category: Provisioning
  subcategory: Automation & Configuration
  status: incubating
  logo: kube-edge.svg
  maturity:
    sandbox_date: 2019-03-18
    incubation_date: 2020-09-16
