apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: KubeVirt
  links:
    - title: Homepage
      url: https://kubevirt.io/
    - title: Crunchbase
      url: https://www.crunchbase.com/organization/cloud-native-computing-foundation
    - title: Twitter
      url: https://twitter.com/kubevirt
    - title: Slack/Discord
      url: https://kubernetes.slack.com/archives/C8ED7RKFE
  tags:
    - virtualization
  annotations:
    backstage.io/source-location: $url:https://github.com/kubevirt/kubevirt
spec:
  type: service
  lifecycle: production
  owner: CNCF
  accepted: 2019-09-06
  category: App Definition and Development
  subcategory: Application Definition & Image Build
  status: incubating
  logo: kubevirt.svg
  maturity:
    sandbox_date: 2019-09-06
    incubation_date: 2022-04-19
