apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: KubeClipper
  description: Manage kubernetes in the most light and convenient way.
  links:
    - title: Homepage
      url: https://www.kubeclipper.io/
    - title: Crunchbase
      url: https://www.crunchbase.com/organization/cloud-native-computing-foundation
  annotations:
    backstage.io/source-location: $url:https://github.com/kubeclipper/kubeclipper
spec:
  type: service
  lifecycle: production
  owner: CNCF
  accepted: 2023-06-30
  category: Platform
  subcategory: Certified Kubernetes - Installer
  status: sandbox
  logo: kubeclipper.svg
  maturity:
    sandbox_date: 2023-06-30
