apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Kube-burner
  links:
    - title: Homepage
      url: https://kube-burner.github.io/kube-burner/
    - title: Crunchbase
      url: https://www.crunchbase.com/organization/red-hat
    - title: Slack/Discord
      url: https://kubernetes.slack.com/messages/kube-burner
  annotations:
    backstage.io/source-location: $url:https://github.com/kube-burner/kube-burner
spec:
  type: service
  lifecycle: production
  owner: CNCF
  accepted: 2023-12-18
  category: App Definition and Development
  subcategory: Continuous Integration & Delivery
  status: sandbox
  logo: kube-burner.svg
  maturity:
    sandbox_date: 2023-12-18
