apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: KusionStack
  links:
    - title: Homepage
      url: https://kusionstack.io/
    - title: Crunchbase
      url: https://www.crunchbase.com/organization/ant-group
    - title: Twitter
      url: https://twitter.com/KusionStack
  annotations:
    backstage.io/source-location: $url:https://github.com/KusionStack/kusion
spec:
  type: service
  lifecycle: production
  owner: CNCF
  accepted: 2024-09-12
  category: Provisioning
  subcategory: Automation & Configuration
  status: sandbox
  logo: kusionstack.svg
  maturity:
    sandbox_date: 2024-09-12
