apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Lima
  description: Linux virtual machines, typically on macOS, for running containerd
  links:
    - title: Homepage
      url: https://github.com/lima-vm/lima
    - title: Crunchbase
      url: https://www.crunchbase.com/organization/cloud-native-computing-foundation
  annotations:
    landscape3.io/accepted: 2022-09-14
    landscape3.io/category: Runtime
    landscape3.io/subcategory: Container Runtime
    landscape3.io/cncfStatus: sandbox
spec:
  type: service
  lifecycle: production
  owner: CNCF
