apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: MetalLB
  links:
    - title: Homepage
      url: https://metallb.universe.tf
    - title: Crunchbase
      url: https://www.crunchbase.com/organization/metallb
  annotations:
    landscape3.io/accepted: 2021-09-14
    landscape3.io/category: Orchestration & Management
    landscape3.io/subcategory: Service Proxy
    landscape3.io/cncfStatus: sandbox
spec:
  type: service
  lifecycle: production
  owner: CNCF
