apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Microcks
  links:
    - title: Homepage
      url: https://microcks.io
    - title: Crunchbase
      url: https://www.crunchbase.com/organization/cloud-native-computing-foundation
    - title: Twitter
      url: https://twitter.com/microcksio
    - title: Slack/Discord
      url: https://cloud-native.slack.com/messages/microcks
  tags:
    - api
    - mocking
    - testing
    - openapi
    - graphql
    - grpc
    - asyncapi
  annotations:
    backstage.io/source-location: $url:https://github.com/microcks/microcks
spec:
  type: service
  lifecycle: production
  owner: CNCF
  accepted: 2023-06-22
  category: App Definition and Development
  subcategory: Application Definition & Image Build
  status: sandbox
  logo: microcks.svg
  maturity:
    sandbox_date: 2023-06-22
