apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Nocalhost
  links:
    - title: Homepage
      url: https://nocalhost.dev
    - title: Crunchbase
      url: https://www.crunchbase.com/organization/cloud-native-computing-foundation
    - title: Slack/Discord
      url: https://cloud-native.slack.com/archives/C02NLKZCJ5D
  annotations:
    backstage.io/source-location: $url:https://github.com/nocalhost/nocalhost
spec:
  type: service
  lifecycle: production
  owner: CNCF
  accepted: 2021-11-16
  category: App Definition and Development
  subcategory: Application Definition & Image Build
  status: sandbox
  logo: nocalhost.svg
  maturity:
    sandbox_date: 2021-11-16
