apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: OpenMetrics
  links:
    - title: Homepage
      url: https://openmetrics.io/
    - title: Crunchbase
      url: https://www.crunchbase.com/organization/cloud-native-computing-foundation
    - title: Twitter
      url: https://twitter.com/OpenMetricsIO
    - title: Slack/Discord
      url: https://cloud-native.slack.com/messages/openmetrics
  annotations:
    backstage.io/source-location: $url:https://github.com/OpenObservability/OpenMetrics
spec:
  type: service
  lifecycle: production
  owner: CNCF
  accepted: 2018-08-10
  category: Observability and Analysis
  subcategory: Observability
  status: incubating
  logo: openmetrics.svg
  maturity:
    sandbox_date: 2018-08-10
    incubation_date: 2022-02-03
