apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: OpenEBS
  links:
    - title: Homepage
      url: https://www.openebs.io/
    - title: Crunchbase
      url: https://www.crunchbase.com/organization/cloud-native-computing-foundation
    - title: Twitter
      url: https://twitter.com/openebs
    - title: Slack/Discord
      url: https://cloud-native.slack.com/archives/CSL0PJ8GN
  annotations:
    backstage.io/source-location: $url:https://github.com/openebs/openebs
spec:
  type: service
  lifecycle: production
  owner: CNCF
  accepted: 2019-05-14
  category: Runtime
  subcategory: Cloud Native Storage
  status: archived
  logo: openebs.svg
  maturity:
    sandbox_date: 2019-05-14
