apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Parsec
  links:
    - title: Homepage
      url: https://parsec.community/
    - title: Crunchbase
      url: https://www.crunchbase.com/organization/cloud-native-computing-foundation
  annotations:
    landscape3.io/accepted: 2020-06-25
    landscape3.io/category: Provisioning
    landscape3.io/subcategory: Security & Compliance
    landscape3.io/cncfStatus: sandbox
spec:
  type: service
  lifecycle: production
  owner: CNCF
