apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Podman-Desktop
  description: An open-source tool for developers to work with containers and
    Kubernetes with an intuitive and user-friendly interface to effortlessly
    build, manage, and deploy containers and Kubernetes — all from the desktop.
  links:
    - title: Homepage
      url: https://podman-desktop.io/
    - title: Crunchbase
      url: https://www.crunchbase.com/organization/cloud-native-computing-foundation
  tags:
    - container
    - kubernetes
    - desktop
    - development
  annotations:
    backstage.io/source-location: $url:https://github.com/podman-desktop/podman-desktop
spec:
  type: service
  lifecycle: production
  owner: CNCF
  accepted: 2025-01-21
  category: App Definition and Development
  subcategory: Application Definition & Image Build
  status: sandbox
  logo: podman-desktop.svg
  maturity:
    sandbox_date: 2025-01-21
