apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: youki
  links:
    - title: Homepage
      url: https://youki-dev.github.io/youki/
    - title: Crunchbase
      url: https://www.crunchbase.com/organization/cloud-native-computing-foundation
    - title: Slack/Discord
      url: https://slack.cncf.io/
  annotations:
    backstage.io/source-location: $url:https://github.com/youki-dev/youki
spec:
  type: service
  lifecycle: production
  owner: CNCF
  accepted: 2024-10-17
  category: Runtime
  subcategory: Container Runtime
  status: sandbox
  logo: youki.svg
  maturity:
    sandbox_date: 2024-10-17
