apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: zot
  description: Zot is an OCI-native container registry for distributing container
    images and OCI artifacts.
  links:
    - title: Homepage
      url: https://zotregistry.dev/
    - title: Crunchbase
      url: https://www.crunchbase.com/organization/cloud-native-computing-foundation
    - title: Twitter
      url: https://twitter.com/zothub
    - title: Slack/Discord
      url: https://cloud-native.slack.com/archives/C03EGRE4QGH
  tags:
    - registry
    - images
    - oci
    - container
    - artifacts
    - vulnerabilityscanning
    - selfhosted
    - zot
    - edge
    - imagesync
  annotations:
    backstage.io/source-location: $url:https://github.com/project-zot/zot
spec:
  type: service
  lifecycle: production
  owner: CNCF
  accepted: 2022-12-13
  category: Provisioning
  subcategory: Container Registry
  status: sandbox
  logo: zot.svg
  maturity:
    sandbox_date: 2022-12-13
