name: Landscape Sync

on:
  schedule:
    - cron:  '0 0 1,15 * *'
  workflow_dispatch:

jobs:
  landscape-sync:
    name: Landscape Sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Install root dependencies
        run: yarn workspaces focus root
      - name: Fetch latest landscape.yml
        run: |
          yarn generate:json
          echo "LANDSCAPE_UPDATED=$(git status -s | grep landscape.json)" >> $GITHUB_ENV
      - name: Generate landscape stats
        if: env.LANDSCAPE_UPDATED
        run: yarn generate:stats
      - name: Generate catalog infos
        if: env.LANDSCAPE_UPDATED
        run: yarn generate:entities
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          base: main
          branch: landscape-sync
          token: ${{ secrets.LANDSCAPE_TOKEN }}
          title: 🚀 Synchronize landscape.yml and regenerate entities [automated]
          body: |
            This pull request was created by the `landscape-sync` [workflow](https://github.com/minkimcello/landscape3/tree/main/.github/workflows).
          author: "lucy-eade <lucy-eade@users.noreply.github.com>"
          committer: "lucy-eade <lucy-eade@users.noreply.github.com>"
          commit-message: |
            Synchronize landscape.yml and update entities [automated]
