name: Tests

on: pull_request

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Install Dependencies
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
