name: Tests

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Install Dependencies
        run: yarn
      - name: Type Check
        run: yarn tsc
      - name: Lint Backstage
        run: yarn lint
      - name: Lint Scripts
        run: yarn lint:scripts
      - name: Test
        run: yarn test
